# Generated by Django 5.2.5 on 2025-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('In- Progress', 'In-progress'), ('Completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
