# Generated by Django 5.2.5 on 2025-08-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_task_created_at_task_description_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In-Progress', 'In-progress'), ('Completed', 'Completed')], default='In-Progress', max_length=20),
        ),
    ]
